apiVersion: v2
name: games-rule-chatbot
description: An umbrella chart for Games Rule Chatbot application
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: cloudnative-pg
    version: 0.26.1
    repository: "https://cloudnative-pg.io/charts/"
  # - name: minio
  #   version: 17.0.21
  #   repository: "https://charts.bitnami.com/bitnami"
