apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
    name: {{ .Release.Name }}-postgres
spec:
    instances: 1
    storage:
        size: 10Gi
    bootstrap:
        initdb:
            database: games
            owner: gamesuser
