apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
    name: {{ .Release.Name }}-postgres
spec:
    instances: 1
    storage:
        size: 10Gi
    bootstrap:
        initdb:
            database: games
            owner: gamesuser
    managed:
      services:
        additional:
          - selectorType: rw
            serviceTemplate:
              metadata:
                name: postgres-lb
                annotations:
                  metallb.universe.tf/loadBalancerIPs: 192.168.0.253
              spec:
                type: LoadBalancer
