apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-creds
  namespace: {{ .Release.Namespace }}
  labels:
      app.kubernetes.io/name: minio-tenant
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  config.env: |-
    export MINIO_ROOT_USER={{ .Values.minio.rootUser | quote }}
    export MINIO_ROOT_PASSWORD={{ .Values.minio.rootPassword | quote }}
